### ISSUE TITLE
Screenshot examples got Xcode error

### ISSUE THREAD

**Issue by impvd** [PerfectoMobileSA/PerfectoXCUITestProject#1]
Hi, I came from https://help.perfecto.io/perfecto-help/content/perfecto/automation-testing/take_screenshots_with_xctest_methods.htm

And thanks for your sharing.

However, it seems that the screenshot examples might not work in Xcode:

<img src="https://user-images.githubusercontent.com/37371804/127580064-b596b70f-3da7-429f-ac8b-6e5bcd82e4cc.png" width=800>

Just wondering if anything I had missed?

**Comment by genesisthomas** [comment]
Dear @impvd , Sorry for the delayed response. Please note that this project is just a sample to showcase how to run XCUITests on Perfecto. Kindly raise a Perfecto support case https://support.perfecto.io 
btw, does this sample help? https://github.com/PerfectoCode/XcTest/tree/master/samples/advancedSamples/EarlGreySample
